"use client";
import {useEffect,useState} from "react";
export type AnalyticsSummary={period_days:number;timezone:string;retention_days:number;generated_at:string;registered:{total:number;today:number;last7:number;last30:number;confirmed:number;incomplete:number};active:{today:number;last7:number;last30:number;selected:number};events:Record<string,number>;top_pages:{event_name:string;views:number}[];daily:{day:string;opens:number;active:number;contacts:number}[];funnel:{opened:number;rates:number;calculated:number;contacted:number};downloads:{status:string;first_time_downloads:number|null;source:string}};
const pages:Record<string,string>={home_viewed:"الرئيسية",rates_viewed:"الأسعار",calculator_viewed:"الحاسبة",offices_viewed:"المكاتب"};
const format=(n:number)=>new Intl.NumberFormat("ar-IQ").format(n);
export default function AppAnalyticsPanel({endpoint}:{endpoint:string}){
 const [days,setDays]=useState(30),[data,setData]=useState<AnalyticsSummary|null>(null),[error,setError]=useState(""),[loading,setLoading]=useState(true);
 useEffect(()=>{const controller=new AbortController();setLoading(true);setError("");fetch(`${endpoint}?days=${days}`,{signal:controller.signal,cache:"no-store"}).then(async r=>{if(!r.ok)throw Error(r.status===403?"لا تملك صلاحية مراقبة التطبيق.":r.status===401?"انتهت جلسة الإدارة.":"تعذر تحميل المراقبة. حاول مجدداً.");return r.json();}).then(x=>setData(x.data)).catch(e=>{if(e.name!=="AbortError")setError(e.message);}).finally(()=>{if(!controller.signal.aborted)setLoading(false);});return()=>controller.abort();},[days,endpoint]);
 const ev=(name:string)=>data?.events[name]??0;
 const metrics=data?[
 ["إجمالي المسجلين",data.registered.total],["تسجيلات اليوم",data.registered.today],["تسجيلات 7 أيام",data.registered.last7],["تسجيلات 30 يوماً",data.registered.last30],
 ["نشطون اليوم",data.active.today],["نشطون 7 أيام",data.active.last7],["نشطون 30 يوماً",data.active.last30],
 ["مرات فتح التطبيق",ev("app_open")],["First Opens · أول فتح",ev("app_first_open")],["استخدام الحاسبة",ev("calculator_used")],["مشاهدة الأسعار",ev("rates_viewed")],["محاولات التواصل",ev("contact_attempted")],
 ["ضغطات WhatsApp",ev("whatsapp_clicked")],["ضغطات الهاتف",ev("phone_clicked")],["ضغطات الموقع",ev("website_clicked")],["مشاهدة المكاتب",ev("offices_viewed")],["اختيار مكتب",ev("office_clicked")],["ضغطات الخرائط",ev("map_clicked")],
 ["تسجيلات مكتملة داخل التطبيق",ev("signup_completed")],["حسابات Auth المؤكدة",data.registered.confirmed],["حسابات غير مؤكدة",data.registered.incomplete]
 ]:[];
 const funnel=data?[data.funnel.opened,data.funnel.rates,data.funnel.calculated,data.funnel.contacted]:[];
 const max=data?Math.max(1,...data.daily.flatMap(d=>[d.opens,d.active,d.contacts])):1;
 return <section className="ur-app-analytics" dir="rtl" aria-busy={loading}>
 <div className="uaa-heading"><div><small>PRODUCT ANALYTICS</small><h2 dir="ltr">UR Global Analytics</h2><p>استخدام التطبيق المعلوماتي · توقيت بغداد</p></div><label>الفترة<select value={days} onChange={e=>setDays(Number(e.target.value))}>{[[1,"اليوم"],[7,"7 أيام"],[30,"30 يوم"],[90,"90 يوم"],[0,"الكل"]].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label></div>
 {error&&<p role="alert" className="uaa-error">{error}</p>}{loading&&<p role="status">جاري تحديث الأرقام…</p>}
 {!loading&&!error&&data&&<>
 <div className="uaa-download"><div><small>APP STORE DOWNLOADS</small><h3>تنزيلات App Store الرسمية</h3><strong>{data.downloads.status==="connected"?format(data.downloads.first_time_downloads??0):"غير مربوط بعد"}</strong><p>المصدر: App Store Connect. أول فتح للتطبيق قياس مستقل، وليس عدد التنزيلات.</p></div><div><small>FIRST OPENS</small><strong>{format(ev("app_first_open"))}</strong><span>أول تشغيل مسجّل لكل تثبيت</span></div></div>
 <div className="uaa-grid">{metrics.map(([title,value])=><article className="uaa-card" key={title}><span>{title}</span><strong>{format(value as number)}</strong></article>)}</div>
 <p className="uaa-note">المسجلون من Supabase Auth في المشروع، وقد يشملون حسابات أنشئت خارج iOS. النشطون تثبيتات فريدة، وليسوا أشخاصاً فريدين بالضرورة. التسجيل المكتمل داخل التطبيق حدث مستقل. «الكل» يشمل البيانات المحتفظ بها خلال {data.retention_days} يوماً. أرقام الفتح والتواصل والمشاهدات تتبع الفترة المختارة.</p>
 <article className="uaa-section"><h3>النشاط اليومي · آخر 30 يوم</h3><div className="uaa-chart" role="img" aria-label="رسم يومي لمرات فتح التطبيق والتثبيتات النشطة ومحاولات التواصل"><svg viewBox="0 0 900 240" direction="ltr">{[0,1,2,3].map(i=><g key={i}><line x1="36" x2="890" y1={205-i*60} y2={205-i*60} stroke="currentColor" opacity=".1"/><text x="0" y={209-i*60} fontSize="11" fill="currentColor">{format(Math.round(max*i/3))}</text></g>)}{data.daily.map((d,i)=><g key={d.day}><rect x={43+i*28} y={205-d.opens/max*180} width="14" height={d.opens/max*180} rx="3" fill="#ba944e"><title>{d.day}: {d.opens} فتح، {d.active} نشط، {d.contacts} تواصل</title></rect>{i%7===0&&<text x={43+i*28} y="231" fontSize="11" fill="currentColor">{d.day.slice(5)}</text>}</g>)}<polyline fill="none" stroke="#438bf5" strokeWidth="3" points={data.daily.map((d,i)=>`${50+i*28},${205-d.active/max*180}`).join(" ")}/><polyline fill="none" stroke="#20a68c" strokeWidth="2" points={data.daily.map((d,i)=>`${50+i*28},${205-d.contacts/max*180}`).join(" ")}/></svg></div><p className="uaa-legend">ذهبي: الفتح · أزرق: النشطون · أخضر: التواصل</p><details><summary>عرض بيانات الرسم</summary><table><thead><tr><th>اليوم</th><th>الفتح</th><th>النشطون</th><th>التواصل</th></tr></thead><tbody>{data.daily.map(d=><tr key={d.day}><td>{d.day}</td><td>{format(d.opens)}</td><td>{format(d.active)}</td><td>{format(d.contacts)}</td></tr>)}</tbody></table></details></article>
 <article className="uaa-section"><h3>مسار التحويل إلى التواصل</h3><p>جلسات مرتبة زمنياً: فتح ← أسعار ← حاسبة ← تواصل. لا يمثل هذا معاملة مالية.</p><div className="uaa-funnel">{["فتح التطبيق","مشاهدة الأسعار","استخدام الحاسبة","محاولة التواصل"].map((title,i)=><div key={title}><span>{title}</span><strong>{format(funnel[i])}</strong><small>{i===0?"بداية المسار":`${funnel[i-1]?(funnel[i]/funnel[i-1]*100).toFixed(1):"0"}% من الخطوة السابقة`}</small><small>{funnel[0]?(funnel[i]/funnel[0]*100).toFixed(1):"0"}% من الفتح</small></div>)}</div></article>
 <article className="uaa-section"><h3>أكثر صفحات التطبيق استخداماً</h3>{data.top_pages.length?<table><thead><tr><th>الصفحة</th><th>المشاهدات</th></tr></thead><tbody>{data.top_pages.map(p=><tr key={p.event_name}><td>{pages[p.event_name]??p.event_name}</td><td>{format(p.views)}</td></tr>)}</tbody></table>:<p>لم تُسجّل مشاهدات خلال هذه الفترة.</p>}</article>
 <p className="uaa-note">آخر تحديث: {new Date(data.generated_at).toLocaleString("ar-IQ",{timeZone:data.timezone})}. يبدأ جمع أحداث iOS عند تشغيل الإصدار المحدّث؛ لا توجد بيانات تاريخية مصطنعة.</p>
 </>}
 </section>;
}
